sudo: false
language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
matrix:
  include:
    - node_js: "7"
      env: TEST_SUITE=standard
    - node_js: "5"
      arch: ppc64le
    - node_js: "6"
      arch: ppc64le
    - node_js: "7"
      arch: ppc64le
    - node_js: "8"
      arch: ppc64le
    - node_js: "7"
      arch: ppc64le
      env: TEST_SUITE=standard

env:
  - TEST_SUITE=unit
script: npm run-script $TEST_SUITE
